environment: "prod"

data:
  input:
    database: "default"
    inference_dataset: "fraud_features_base"
  output:
    database: "default"
    scored_inference_dataset: "fraud_scored_inference_dataset"

model:
  model_name: "FraudXGB"
  experiment_name: "/Shared/fraud-xgboost-pkg_experiment"
  hyperparameters_grid:
    max_depth: [3, 10]
    n_estimators: [30, 50]
    # max_features: ["auto"]
    # criterion: ["gini", "entropy"]
  hyperparameters_fixed:
    # class_weight: "balanced"
    use_label_encoder: "False"
    eval_metric: "logloss"
    random_state: "7"
  minimal_threshold: 0.8