environment: "dev"

data:
  input:
    database: "default"
    train_dataset: "fraud_train_dataset"
    test_dataset: "fraud_test_dataset"
    scored_inference_dataset: "fraud_scored_inference_dataset"  
    label_table: "fraud_labels"  
  output:
    database: "default"
    data_monitoring: "fraud_data_monitoring" 
    performance_monitoring: "fraud_performance_monitoring"

model:
  model_name: "FraudXGB"
  experiment_name: "/Shared/fraud-xgboost-pkg_experiment"
  hyperparameters_grid:
    max_depth: [3, 10]
    n_estimators: [30, 50]
    # max_features: ["auto"]
    # criterion: ["gini", "entropy"]
  hyperparameters_fixed:
    # class_weight: "balanced"
    use_label_encoder: "False"
    eval_metric: "logloss"
    random_state: "7"
  minimal_threshold: 0.8