environment: "dev"

data:
  input:
    database: "default"
    raw_data_table: "fraud_features_base" 
    enrich1: "fraud_features_enrich1"
    enrich2: "fraud_features_enrich2"
    label_table: "fraud_label" 
    fs_database: "fraud_feature_store"
    fs_table: "enrich_features"
  output:
    database: "default"
    random_state: "92"
    train_size: "0.7"
    train_dataset: "fraud_train_dataset"
    test_dataset: "fraud_test_dataset"

model:
  model_name: "FraudXGB"
  experiment_name: "/Shared/fraud-xgboost-pkg_experiment"
  hyperparameters_grid:
    max_depth: [3, 10]
    n_estimators: [30, 50]
    # max_features: ["auto"]
    # criterion: ["gini", "entropy"]
  hyperparameters_fixed:
    # class_weight: "balanced"
    use_label_encoder: "False"
    eval_metric: "logloss"
    random_state: "7"
  minimal_threshold: 0.8